<a href="https://colab.research.google.com/github/Divasdev/-100-Days-of-Code-Python-Pro-Bootcamp/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [196]:
dict1={
    "Students":['Ruckhika A','Neha B',"Mark C",'Divas D','Jamaal E'],

     "Subjects":["Maths","Phy","chem","Bio",'Geo'],
    'Marks':[79.5,83.75,74,88.5,89],
    'Sports':['Cricket','Badminton','Football','Athelitics','Tennis'],
    'email':["ruchhika@gamil.com",'nehas@gamil.com','marks@gamil.com','divas@gmail.com','jammaal@gamil.com']
}

In [197]:
import pandas as pd
import numpy as np

In [198]:
df1=pd.DataFrame(dict1)
df1

     Students Subjects  Marks      Sports               email
0  Ruckhika A    Maths  79.50     Cricket  ruchhika@gamil.com
1      Neha B      Phy  83.75   Badminton     nehas@gamil.com
2      Mark C     chem  74.00    Football     marks@gamil.com
3     Divas D      Bio  88.50  Athelitics     divas@gmail.com
4    Jamaal E      Geo  89.00      Tennis   jammaal@gamil.com

In [199]:
type(df1["Sports"])

pandas.core.series.Series

In [200]:
df1.Students

0    Ruckhika A
1        Neha B
2        Mark C
3       Divas D
4      Jamaal E
Name: Students, dtype: object

In [201]:
df1[['Marks',"Sports"]]

   Marks      Sports
0  79.50     Cricket
1  83.75   Badminton
2  74.00    Football
3  88.50  Athelitics
4  89.00      Tennis

In [202]:
df1.columns

Index(['Students', 'Subjects', 'Marks', 'Sports', 'email'], dtype='object')

In [203]:
df1.iloc[[0,1],[0,2]]

     Students  Marks
0  Ruckhika A  79.50
1      Neha B  83.75

In [204]:
df1.loc[[0,3],["Students","Marks"]]

     Students  Marks
0  Ruckhika A   79.5
3     Divas D   88.5

In [205]:
df1

     Students Subjects  Marks      Sports               email
0  Ruckhika A    Maths  79.50     Cricket  ruchhika@gamil.com
1      Neha B      Phy  83.75   Badminton     nehas@gamil.com
2      Mark C     chem  74.00    Football     marks@gamil.com
3     Divas D      Bio  88.50  Athelitics     divas@gmail.com
4    Jamaal E      Geo  89.00      Tennis   jammaal@gamil.com

In [206]:
df1

     Students Subjects  Marks      Sports               email
0  Ruckhika A    Maths  79.50     Cricket  ruchhika@gamil.com
1      Neha B      Phy  83.75   Badminton     nehas@gamil.com
2      Mark C     chem  74.00    Football     marks@gamil.com
3     Divas D      Bio  88.50  Athelitics     divas@gmail.com
4    Jamaal E      Geo  89.00      Tennis   jammaal@gamil.com

In [207]:
df1["Sports"]

0       Cricket
1     Badminton
2      Football
3    Athelitics
4        Tennis
Name: Sports, dtype: object

In [208]:
df1.set_index("Sports",inplace=True)

In [209]:
df1

              Students Subjects  Marks               email
Sports
Cricket     Ruckhika A    Maths  79.50  ruchhika@gamil.com
Badminton       Neha B      Phy  83.75     nehas@gamil.com
Football        Mark C     chem  74.00     marks@gamil.com
Athelitics     Divas D      Bio  88.50     divas@gmail.com
Tennis        Jamaal E      Geo  89.00   jammaal@gamil.com

In [210]:
df1.index

Index(['Cricket', 'Badminton', 'Football', 'Athelitics', 'Tennis'], dtype='object', name='Sports')

In [211]:
df1.loc["Cricket"]

Students            Ruckhika A
Subjects                 Maths
Marks                     79.5
email       ruchhika@gamil.com
Name: Cricket, dtype: object

In [212]:
df1.reset_index(inplace=True)

In [213]:
df1

       Sports    Students Subjects  Marks               email
0     Cricket  Ruckhika A    Maths  79.50  ruchhika@gamil.com
1   Badminton      Neha B      Phy  83.75     nehas@gamil.com
2    Football      Mark C     chem  74.00     marks@gamil.com
3  Athelitics     Divas D      Bio  88.50     divas@gmail.com
4      Tennis    Jamaal E      Geo  89.00   jammaal@gamil.com

In [214]:
filt=((df1["Sports"]=="Cricket") & (df1['Subjects']=='Maths' ))

In [215]:
df1[~filt]

       Sports  Students Subjects  Marks              email
1   Badminton    Neha B      Phy  83.75    nehas@gamil.com
2    Football    Mark C     chem  74.00    marks@gamil.com
3  Athelitics   Divas D      Bio  88.50    divas@gmail.com
4      Tennis  Jamaal E      Geo  89.00  jammaal@gamil.com

In [216]:
df1.columns

Index(['Sports', 'Students', 'Subjects', 'Marks', 'email'], dtype='object')

In [217]:
df1.columns=["Sports",'Name','Sub','Marks','gamil']
df1

       Sports        Name    Sub  Marks               gamil
0     Cricket  Ruckhika A  Maths  79.50  ruchhika@gamil.com
1   Badminton      Neha B    Phy  83.75     nehas@gamil.com
2    Football      Mark C   chem  74.00     marks@gamil.com
3  Athelitics     Divas D    Bio  88.50     divas@gmail.com
4      Tennis    Jamaal E    Geo  89.00   jammaal@gamil.com

In [218]:
df1.columns=[x.upper() for x in df1.columns]
df1

       SPORTS        NAME    SUB  MARKS               GAMIL
0     Cricket  Ruckhika A  Maths  79.50  ruchhika@gamil.com
1   Badminton      Neha B    Phy  83.75     nehas@gamil.com
2    Football      Mark C   chem  74.00     marks@gamil.com
3  Athelitics     Divas D    Bio  88.50     divas@gmail.com
4      Tennis    Jamaal E    Geo  89.00   jammaal@gamil.com

In [219]:
df1.columns=df1.columns.str.replace(' ',"_")

In [220]:
df1

       SPORTS        NAME    SUB  MARKS               GAMIL
0     Cricket  Ruckhika A  Maths  79.50  ruchhika@gamil.com
1   Badminton      Neha B    Phy  83.75     nehas@gamil.com
2    Football      Mark C   chem  74.00     marks@gamil.com
3  Athelitics     Divas D    Bio  88.50     divas@gmail.com
4      Tennis    Jamaal E    Geo  89.00   jammaal@gamil.com

In [221]:
df1.loc[3]=["Hockey",'Raj','CS','90',"raj@gamil.com"]
df1

/tmp/ipykernel_1996/3098241938.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '90' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df1.loc[3]=["Hockey",'Raj','CS','90',"raj@gamil.com"]

      SPORTS        NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika A  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha B    Phy  83.75     nehas@gamil.com
2   Football      Mark C   chem   74.0     marks@gamil.com
3     Hockey         Raj     CS     90       raj@gamil.com
4     Tennis    Jamaal E    Geo   89.0   jammaal@gamil.com

In [222]:
df1.loc[2,['NAME','GAMIL']]=['Doe','johdoe@email.com']
df1

      SPORTS        NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika A  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha B    Phy  83.75     nehas@gamil.com
2   Football         Doe   chem   74.0    johdoe@email.com
3     Hockey         Raj     CS     90       raj@gamil.com
4     Tennis    Jamaal E    Geo   89.0   jammaal@gamil.com

In [223]:
df1.loc[4,'NAME']='Smith'

In [224]:
df1

      SPORTS        NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika A  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha B    Phy  83.75     nehas@gamil.com
2   Football         Doe   chem   74.0    johdoe@email.com
3     Hockey         Raj     CS     90       raj@gamil.com
4     Tennis       Smith    Geo   89.0   jammaal@gamil.com

In [225]:
df1.at[4,'NAME']='Virat'
df1

      SPORTS        NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika A  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha B    Phy  83.75     nehas@gamil.com
2   Football         Doe   chem   74.0    johdoe@email.com
3     Hockey         Raj     CS     90       raj@gamil.com
4     Tennis       Virat    Geo   89.0   jammaal@gamil.com

In [226]:
filt=(df1['NAME']=='Raj')
df1[filt]['GAMIL']='raj@email.com'

/tmp/ipykernel_1996/2587963784.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[filt]['GAMIL']='raj@email.com'

In [227]:
filt=(df1['NAME']=='Raj')
df1.loc[filt,'GAMIL']='raj@email.com'
df1['NAME']=df1['NAME'].str.lower()
df1

      SPORTS        NAME    SUB  MARKS               GAMIL
0    Cricket  ruckhika a  Maths   79.5  ruchhika@gamil.com
1  Badminton      neha b    Phy  83.75     nehas@gamil.com
2   Football         doe   chem   74.0    johdoe@email.com
3     Hockey         raj     CS     90       raj@email.com
4     Tennis       virat    Geo   89.0   jammaal@gamil.com

In [228]:
#apply- use for calling function in values
#map
#applymap
#replace

In [229]:
df1['GAMIL'].apply(len)

0    18
1    15
2    16
3    13
4    17
Name: GAMIL, dtype: int64

In [230]:
def update_email(email):
  return email.upper()

In [231]:
df1['GAMIL']=df1['GAMIL'].apply(update_email)
df1

      SPORTS        NAME    SUB  MARKS               GAMIL
0    Cricket  ruckhika a  Maths   79.5  RUCHHIKA@GAMIL.COM
1  Badminton      neha b    Phy  83.75     NEHAS@GAMIL.COM
2   Football         doe   chem   74.0    JOHDOE@EMAIL.COM
3     Hockey         raj     CS     90       RAJ@EMAIL.COM
4     Tennis       virat    Geo   89.0   JAMMAAL@GAMIL.COM

In [232]:
df1['GAMIL']=df1['GAMIL'].apply(lambda x: x.lower())
df1

      SPORTS        NAME    SUB  MARKS               GAMIL
0    Cricket  ruckhika a  Maths   79.5  ruchhika@gamil.com
1  Badminton      neha b    Phy  83.75     nehas@gamil.com
2   Football         doe   chem   74.0    johdoe@email.com
3     Hockey         raj     CS     90       raj@email.com
4     Tennis       virat    Geo   89.0   jammaal@gamil.com

In [233]:
df1.apply(len,axis='columns')

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [234]:
len(df1['NAME'])

5

In [235]:
# To find min, we should exclude non-numeric columns or ensure types are compatible
display(df1.min(numeric_only=True))

Series([], dtype: float64)

In [236]:
# Use .map (replacement for applymap) and convert to string first to avoid float errors
display(df1.astype(str).map(len))

   SPORTS  NAME  SUB  MARKS  GAMIL
0       7    10    5      4     18
1       9     6    3      5     15
2       8     3    4      4     16
3       6     3    2      2     13
4       6     5    3      4     17

In [237]:
# To use lower, only apply it to columns that are actually strings
display(df1.astype(str).map(str.lower))

      SPORTS        NAME    SUB  MARKS               GAMIL
0    cricket  ruckhika a  maths   79.5  ruchhika@gamil.com
1  badminton      neha b    phy  83.75     nehas@gamil.com
2   football         doe   chem   74.0    johdoe@email.com
3     hockey         raj     cs     90       raj@email.com
4     tennis       virat    geo   89.0   jammaal@gamil.com

In [238]:
df1['NAME'].map({'doe':'John','raj':'christ'})
df1

      SPORTS        NAME    SUB  MARKS               GAMIL
0    Cricket  ruckhika a  Maths   79.5  ruchhika@gamil.com
1  Badminton      neha b    Phy  83.75     nehas@gamil.com
2   Football         doe   chem   74.0    johdoe@email.com
3     Hockey         raj     CS     90       raj@email.com
4     Tennis       virat    Geo   89.0   jammaal@gamil.com

In [239]:
df1['NAME']=df1['NAME'].replace({'doe':'John','raj':'christ'})

In [240]:
df1

      SPORTS        NAME    SUB  MARKS               GAMIL
0    Cricket  ruckhika a  Maths   79.5  ruchhika@gamil.com
1  Badminton      neha b    Phy  83.75     nehas@gamil.com
2   Football        John   chem   74.0    johdoe@email.com
3     Hockey      christ     CS     90       raj@email.com
4     Tennis       virat    Geo   89.0   jammaal@gamil.com

In [241]:
df1["NAME"]+" "+df1["SUB"]

0    ruckhika a Maths
1          neha b Phy
2           John chem
3           christ CS
4           virat Geo
dtype: object

In [242]:
df1["name_sub"]=df1["NAME"]+" "+df1["SUB"]
df1

      SPORTS        NAME    SUB  MARKS               GAMIL          name_sub
0    Cricket  ruckhika a  Maths   79.5  ruchhika@gamil.com  ruckhika a Maths
1  Badminton      neha b    Phy  83.75     nehas@gamil.com        neha b Phy
2   Football        John   chem   74.0    johdoe@email.com         John chem
3     Hockey      christ     CS     90       raj@email.com         christ CS
4     Tennis       virat    Geo   89.0   jammaal@gamil.com         virat Geo

In [243]:

df1.drop(columns=['GAMIL'],inplace=True)
df1

      SPORTS        NAME    SUB  MARKS          name_sub
0    Cricket  ruckhika a  Maths   79.5  ruckhika a Maths
1  Badminton      neha b    Phy  83.75        neha b Phy
2   Football        John   chem   74.0         John chem
3     Hockey      christ     CS     90         christ CS
4     Tennis       virat    Geo   89.0         virat Geo

In [244]:
df1["NAME"].str.split(" ",expand=True)

          0     1
0  ruckhika     a
1      neha     b
2      John  None
3    christ  None
4     virat  None

In [245]:
df1[['first','last']]=df1["NAME"].str.split(" ",expand=True)
df1

      SPORTS        NAME    SUB  MARKS          name_sub     first  last
0    Cricket  ruckhika a  Maths   79.5  ruckhika a Maths  ruckhika     a
1  Badminton      neha b    Phy  83.75        neha b Phy      neha     b
2   Football        John   chem   74.0         John chem      John  None
3     Hockey      christ     CS     90         christ CS    christ  None
4     Tennis       virat    Geo   89.0         virat Geo     virat  None

In [246]:
df1 = pd.concat([df1, pd.DataFrame([{"SPORTS":"Hockey"}])], ignore_index=True)
df1

      SPORTS        NAME    SUB  MARKS          name_sub     first  last
0    Cricket  ruckhika a  Maths   79.5  ruckhika a Maths  ruckhika     a
1  Badminton      neha b    Phy  83.75        neha b Phy      neha     b
2   Football        John   chem   74.0         John chem      John  None
3     Hockey      christ     CS     90         christ CS    christ  None
4     Tennis       virat    Geo   89.0         virat Geo     virat  None
5     Hockey         NaN    NaN    NaN               NaN       NaN   NaN

In [247]:
dict1={
    "Students":['Ruckhika A','Neha B',"Mark C",'Divas D','Jamaal E'],
     "Subjects":["Maths","Phy","chem","Bio",'Geo'],
    "College":["IITM",'IITB','IITD','IITKGP','IITG'],
    'Marks':[79.5,83.75,74,88.5,89],

}
df2 = pd.DataFrame(dict1)
display(df2.head())

     Students Subjects College  Marks
0  Ruckhika A    Maths    IITM  79.50
1      Neha B      Phy    IITB  83.75
2      Mark C     chem    IITD  74.00
3     Divas D      Bio  IITKGP  88.50
4    Jamaal E      Geo    IITG  89.00

In [248]:
df1 = pd.concat([df1, df2], ignore_index=True)
df1

,SPORTS,NAME,SUB,MARKS,name_sub,first,last,Students,Subjects,College,Marks
0,Cricket,ruckhika a,Maths,79.5,ruckhika a Maths,ruckhika,a,NaN,NaN,NaN,NaN
1,Badminton,neha b,Phy,83.75,neha b Phy,neha,b,NaN,NaN,NaN,NaN
2,Football,John,chem,74.0,John chem,John,None,NaN,NaN,NaN,NaN
3,Hockey,christ,CS,90,christ CS,christ,None,NaN,NaN,NaN,NaN
4,Tennis,virat,Geo,89.0,virat Geo,virat,None,NaN,NaN,NaN,NaN
5,Hockey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ruckhika A,Maths,IITM,79.50
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neha B,Phy,IITB,83.75
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mark C,chem,IITD,74.00
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Divas D,Bio,IITKGP,88.50
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jamaal E,Geo,IITG,89.00

In [249]:
data = {

    "First_Name": ["Aman", "Riya", "Kabir", np.nan, "Neel"],
    "Last_Name": ["Sharma", "Gupta", "Khan", np.nan, "Patel"],
    "Age": [21, 19, 22, "NA", 23],
    "Course": ["DS", "AI", "Web", None, "AI"],
    "Marks": [88, 92, 76, None, "Missing"]
}
df = pd.DataFrame(data)

df.replace('NA',np.nan,inplace=True)
df.replace('Missing',np.nan,inplace=True)
df

/tmp/ipykernel_1996/3894021914.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('NA',np.nan,inplace=True)
/tmp/ipykernel_1996/3894021914.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('Missing',np.nan,inplace=True)

  First_Name Last_Name   Age Course  Marks
0       Aman    Sharma  21.0     DS   88.0
1       Riya     Gupta  19.0     AI   92.0
2      Kabir      Khan  22.0    Web   76.0
3        NaN       NaN   NaN   None    NaN
4       Neel     Patel  23.0     AI    NaN

In [250]:
df.sort_values(by='Last_Name',ascending=False)

  First_Name Last_Name   Age Course  Marks
0       Aman    Sharma  21.0     DS   88.0
4       Neel     Patel  23.0     AI    NaN
2      Kabir      Khan  22.0    Web   76.0
1       Riya     Gupta  19.0     AI   92.0
3        NaN       NaN   NaN   None    NaN

In [251]:
df.sort_values(by=['Age'],ascending=False)

  First_Name Last_Name   Age Course  Marks
4       Neel     Patel  23.0     AI    NaN
2      Kabir      Khan  22.0    Web   76.0
0       Aman    Sharma  21.0     DS   88.0
1       Riya     Gupta  19.0     AI   92.0
3        NaN       NaN   NaN   None    NaN

In [252]:
df.sort_values(by=['Age','Marks'],ascending=[False,True],inplace=True)
df

  First_Name Last_Name   Age Course  Marks
4       Neel     Patel  23.0     AI    NaN
2      Kabir      Khan  22.0    Web   76.0
0       Aman    Sharma  21.0     DS   88.0
1       Riya     Gupta  19.0     AI   92.0
3        NaN       NaN   NaN   None    NaN

In [253]:
df.sort_index()

  First_Name Last_Name   Age Course  Marks
0       Aman    Sharma  21.0     DS   88.0
1       Riya     Gupta  19.0     AI   92.0
2      Kabir      Khan  22.0    Web   76.0
3        NaN       NaN   NaN   None    NaN
4       Neel     Patel  23.0     AI    NaN

In [254]:
df["Last_Name"].sort_values()

1     Gupta
2      Khan
4     Patel
0    Sharma
3       NaN
Name: Last_Name, dtype: object

In [255]:
df.dropna()

  First_Name Last_Name   Age Course  Marks
2      Kabir      Khan  22.0    Web   76.0
0       Aman    Sharma  21.0     DS   88.0
1       Riya     Gupta  19.0     AI   92.0

In [256]:
df.dropna(axis='index',how='any',subset=['Marks'])

  First_Name Last_Name   Age Course  Marks
2      Kabir      Khan  22.0    Web   76.0
0       Aman    Sharma  21.0     DS   88.0
1       Riya     Gupta  19.0     AI   92.0

In [257]:
df.isna()

   First_Name  Last_Name    Age  Course  Marks
4       False      False  False   False   True
2       False      False  False   False  False
0       False      False  False   False  False
1       False      False  False   False  False
3        True       True   True    True   True

In [258]:
df.fillna(0)

  First_Name Last_Name   Age Course  Marks
4       Neel     Patel  23.0     AI    0.0
2      Kabir      Khan  22.0    Web   76.0
0       Aman    Sharma  21.0     DS   88.0
1       Riya     Gupta  19.0     AI   92.0
3          0         0   0.0      0    0.0

In [259]:
df.dtypes

First_Name     object
Last_Name      object
Age           float64
Course         object
Marks         float64
dtype: object

In [261]:
df['Age'].mean()

np.float64(21.25)