<a href="https://colab.research.google.com/github/Divasdev/-100-Days-of-Code-Python-Pro-Bootcamp/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
dict1={
    "Students":['Ruckhika','Neha',"Mark",'Divas','Jamaal'],
     "Subjects":["Maths","Phy","chem","Bio",'Geo'],
    'Marks':[79.5,83.75,74,88.5,89],
    'Sports':['Cricket','Badminton','Football','Athelitics','Tennis'],
    'email':["ruchhika@gamil.com",'nehas@gamil.com','marks@gamil.com','divas@gmail.com','jammaal@gamil.com']
}

In [30]:
import pandas as pd

In [31]:
df1=pd.DataFrame(dict1)
df1

   Students Subjects  Marks      Sports               email
0  Ruckhika    Maths  79.50     Cricket  ruchhika@gamil.com
1      Neha      Phy  83.75   Badminton     nehas@gamil.com
2      Mark     chem  74.00    Football     marks@gamil.com
3     Divas      Bio  88.50  Athelitics     divas@gmail.com
4    Jamaal      Geo  89.00      Tennis   jammaal@gamil.com

In [32]:
type(df1["Sports"])

pandas.core.series.Series

In [33]:
df1.Students

0    Ruckhika
1        Neha
2        Mark
3       Divas
4      Jamaal
Name: Students, dtype: object

In [34]:
df1[['Marks',"Sports"]]

   Marks      Sports
0  79.50     Cricket
1  83.75   Badminton
2  74.00    Football
3  88.50  Athelitics
4  89.00      Tennis

In [35]:
df1.columns

Index(['Students', 'Subjects', 'Marks', 'Sports', 'email'], dtype='object')

In [36]:
df1.iloc[[0,1],[0,2]]

   Students  Marks
0  Ruckhika  79.50
1      Neha  83.75

In [37]:
df1.loc[[0,3],["Students","Marks"]]

   Students  Marks
0  Ruckhika   79.5
3     Divas   88.5

In [38]:
df1

   Students Subjects  Marks      Sports               email
0  Ruckhika    Maths  79.50     Cricket  ruchhika@gamil.com
1      Neha      Phy  83.75   Badminton     nehas@gamil.com
2      Mark     chem  74.00    Football     marks@gamil.com
3     Divas      Bio  88.50  Athelitics     divas@gmail.com
4    Jamaal      Geo  89.00      Tennis   jammaal@gamil.com

In [39]:
df1

   Students Subjects  Marks      Sports               email
0  Ruckhika    Maths  79.50     Cricket  ruchhika@gamil.com
1      Neha      Phy  83.75   Badminton     nehas@gamil.com
2      Mark     chem  74.00    Football     marks@gamil.com
3     Divas      Bio  88.50  Athelitics     divas@gmail.com
4    Jamaal      Geo  89.00      Tennis   jammaal@gamil.com

In [40]:
df1["Sports"]

0       Cricket
1     Badminton
2      Football
3    Athelitics
4        Tennis
Name: Sports, dtype: object

In [41]:
df1.set_index("Sports",inplace=True)

In [42]:
df1

            Students Subjects  Marks               email
Sports
Cricket     Ruckhika    Maths  79.50  ruchhika@gamil.com
Badminton       Neha      Phy  83.75     nehas@gamil.com
Football        Mark     chem  74.00     marks@gamil.com
Athelitics     Divas      Bio  88.50     divas@gmail.com
Tennis        Jamaal      Geo  89.00   jammaal@gamil.com

In [43]:
df1.index

Index(['Cricket', 'Badminton', 'Football', 'Athelitics', 'Tennis'], dtype='object', name='Sports')

In [44]:
df1.loc["Cricket"]

Students              Ruckhika
Subjects                 Maths
Marks                     79.5
email       ruchhika@gamil.com
Name: Cricket, dtype: object

In [45]:
df1.reset_index(inplace=True)

In [46]:
df1

       Sports  Students Subjects  Marks               email
0     Cricket  Ruckhika    Maths  79.50  ruchhika@gamil.com
1   Badminton      Neha      Phy  83.75     nehas@gamil.com
2    Football      Mark     chem  74.00     marks@gamil.com
3  Athelitics     Divas      Bio  88.50     divas@gmail.com
4      Tennis    Jamaal      Geo  89.00   jammaal@gamil.com

In [47]:
filt=((df1["Sports"]=="Cricket") & (df1['Subjects']=='Maths' ))

In [48]:
df1[~filt]

       Sports Students Subjects  Marks              email
1   Badminton     Neha      Phy  83.75    nehas@gamil.com
2    Football     Mark     chem  74.00    marks@gamil.com
3  Athelitics    Divas      Bio  88.50    divas@gmail.com
4      Tennis   Jamaal      Geo  89.00  jammaal@gamil.com

In [49]:
df1.columns

Index(['Sports', 'Students', 'Subjects', 'Marks', 'email'], dtype='object')

In [50]:
df1.columns=["Sports",'Name','Sub','Marks','gamil']
df1

       Sports      Name    Sub  Marks               gamil
0     Cricket  Ruckhika  Maths  79.50  ruchhika@gamil.com
1   Badminton      Neha    Phy  83.75     nehas@gamil.com
2    Football      Mark   chem  74.00     marks@gamil.com
3  Athelitics     Divas    Bio  88.50     divas@gmail.com
4      Tennis    Jamaal    Geo  89.00   jammaal@gamil.com

In [51]:
df1.columns=[x.upper() for x in df1.columns]
df1

       SPORTS      NAME    SUB  MARKS               GAMIL
0     Cricket  Ruckhika  Maths  79.50  ruchhika@gamil.com
1   Badminton      Neha    Phy  83.75     nehas@gamil.com
2    Football      Mark   chem  74.00     marks@gamil.com
3  Athelitics     Divas    Bio  88.50     divas@gmail.com
4      Tennis    Jamaal    Geo  89.00   jammaal@gamil.com

In [52]:
df1.columns=df1.columns.str.replace(' ',"_")

In [53]:
df1

       SPORTS      NAME    SUB  MARKS               GAMIL
0     Cricket  Ruckhika  Maths  79.50  ruchhika@gamil.com
1   Badminton      Neha    Phy  83.75     nehas@gamil.com
2    Football      Mark   chem  74.00     marks@gamil.com
3  Athelitics     Divas    Bio  88.50     divas@gmail.com
4      Tennis    Jamaal    Geo  89.00   jammaal@gamil.com

In [54]:
df1.loc[3]=["Hockey",'Raj','CS','90',"raj@gamil.com"]
df1

/tmp/ipykernel_8879/3098241938.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '90' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df1.loc[3]=["Hockey",'Raj','CS','90',"raj@gamil.com"]

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha    Phy  83.75     nehas@gamil.com
2   Football      Mark   chem   74.0     marks@gamil.com
3     Hockey       Raj     CS     90       raj@gamil.com
4     Tennis    Jamaal    Geo   89.0   jammaal@gamil.com

In [55]:
df1.loc[2,['NAME','GAMIL']]=['Doe','johdoe@email.com']
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha    Phy  83.75     nehas@gamil.com
2   Football       Doe   chem   74.0    johdoe@email.com
3     Hockey       Raj     CS     90       raj@gamil.com
4     Tennis    Jamaal    Geo   89.0   jammaal@gamil.com

In [56]:
df1.loc[4,'NAME']='Smith'

In [57]:
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha    Phy  83.75     nehas@gamil.com
2   Football       Doe   chem   74.0    johdoe@email.com
3     Hockey       Raj     CS     90       raj@gamil.com
4     Tennis     Smith    Geo   89.0   jammaal@gamil.com

In [58]:
df1.at[4,'NAME']='Virat'
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha    Phy  83.75     nehas@gamil.com
2   Football       Doe   chem   74.0    johdoe@email.com
3     Hockey       Raj     CS     90       raj@gamil.com
4     Tennis     Virat    Geo   89.0   jammaal@gamil.com

In [59]:
filt=(df1['NAME']=='Raj')
df1[filt]['GAMIL']='raj@email.com'

/tmp/ipykernel_8879/2587963784.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[filt]['GAMIL']='raj@email.com'

In [60]:
filt=(df1['NAME']=='Raj')
df1.loc[filt,'GAMIL']='raj@email.com'
df1['NAME']=df1['NAME'].str.lower()
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      neha    Phy  83.75     nehas@gamil.com
2   Football       doe   chem   74.0    johdoe@email.com
3     Hockey       raj     CS     90       raj@email.com
4     Tennis     virat    Geo   89.0   jammaal@gamil.com

In [61]:
#apply- use for calling function in values
#map
#applymap
#replace

In [62]:
df1['GAMIL'].apply(len)

0    18
1    15
2    16
3    13
4    17
Name: GAMIL, dtype: int64

In [63]:
def update_email(email):
  return email.upper()

In [64]:
df1['GAMIL']=df1['GAMIL'].apply(update_email)
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  ruckhika  Maths   79.5  RUCHHIKA@GAMIL.COM
1  Badminton      neha    Phy  83.75     NEHAS@GAMIL.COM
2   Football       doe   chem   74.0    JOHDOE@EMAIL.COM
3     Hockey       raj     CS     90       RAJ@EMAIL.COM
4     Tennis     virat    Geo   89.0   JAMMAAL@GAMIL.COM

In [65]:
df1['GAMIL']=df1['GAMIL'].apply(lambda x: x.lower())
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      neha    Phy  83.75     nehas@gamil.com
2   Football       doe   chem   74.0    johdoe@email.com
3     Hockey       raj     CS     90       raj@email.com
4     Tennis     virat    Geo   89.0   jammaal@gamil.com

In [66]:
df1.apply(len,axis='columns')

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [67]:
len(df1['NAME'])

5

In [68]:
# To find min, we should exclude non-numeric columns or ensure types are compatible
display(df1.min(numeric_only=True))

Series([], dtype: float64)

In [69]:
# Use .map (replacement for applymap) and convert to string first to avoid float errors
display(df1.astype(str).map(len))

   SPORTS  NAME  SUB  MARKS  GAMIL
0       7     8    5      4     18
1       9     4    3      5     15
2       8     3    4      4     16
3       6     3    2      2     13
4       6     5    3      4     17

In [70]:
# To use lower, only apply it to columns that are actually strings
display(df1.astype(str).map(str.lower))

      SPORTS      NAME    SUB  MARKS               GAMIL
0    cricket  ruckhika  maths   79.5  ruchhika@gamil.com
1  badminton      neha    phy  83.75     nehas@gamil.com
2   football       doe   chem   74.0    johdoe@email.com
3     hockey       raj     cs     90       raj@email.com
4     tennis     virat    geo   89.0   jammaal@gamil.com

In [71]:
df1['NAME'].map({'doe':'John','raj':'christ'})
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      neha    Phy  83.75     nehas@gamil.com
2   Football       doe   chem   74.0    johdoe@email.com
3     Hockey       raj     CS     90       raj@email.com
4     Tennis     virat    Geo   89.0   jammaal@gamil.com

In [72]:
df1['NAME']=df1['NAME'].replace({'doe':'John','raj':'christ'})

In [73]:
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      neha    Phy  83.75     nehas@gamil.com
2   Football      John   chem   74.0    johdoe@email.com
3     Hockey    christ     CS     90       raj@email.com
4     Tennis     virat    Geo   89.0   jammaal@gamil.com