<a href="https://colab.research.google.com/github/Divasdev/-100-Days-of-Code-Python-Pro-Bootcamp/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
dict1={
    "Students":['Ruckhika','Neha',"Mark",'Divas','Jamaal'],
     "Subjects":["Maths","Phy","chem","Bio",'Geo'],
    'Marks':[79.5,83.75,74,88.5,89],
    'Sports':['Cricket','Badminton','Football','Athelitics','Tennis'],
    'email':["ruchhika@gamil.com",'nehas@gamil.com','marks@gamil.com','divas@gmail.com','jammaal@gamil.com']
}

In [57]:
import pandas as pd

In [58]:
df1=pd.DataFrame(dict1)
df1

   Students Subjects  Marks      Sports               email
0  Ruckhika    Maths  79.50     Cricket  ruchhika@gamil.com
1      Neha      Phy  83.75   Badminton     nehas@gamil.com
2      Mark     chem  74.00    Football     marks@gamil.com
3     Divas      Bio  88.50  Athelitics     divas@gmail.com
4    Jamaal      Geo  89.00      Tennis   jammaal@gamil.com

In [59]:
type(df1["Sports"])

pandas.core.series.Series

In [60]:
df1.Students

0    Ruckhika
1        Neha
2        Mark
3       Divas
4      Jamaal
Name: Students, dtype: object

In [61]:
df1[['Marks',"Sports"]]

   Marks      Sports
0  79.50     Cricket
1  83.75   Badminton
2  74.00    Football
3  88.50  Athelitics
4  89.00      Tennis

In [62]:
df1.columns

Index(['Students', 'Subjects', 'Marks', 'Sports', 'email'], dtype='object')

In [63]:
df1.iloc[[0,1],[0,2]]

   Students  Marks
0  Ruckhika  79.50
1      Neha  83.75

In [64]:
df1.loc[[0,3],["Students","Marks"]]

   Students  Marks
0  Ruckhika   79.5
3     Divas   88.5

In [65]:
df1

   Students Subjects  Marks      Sports               email
0  Ruckhika    Maths  79.50     Cricket  ruchhika@gamil.com
1      Neha      Phy  83.75   Badminton     nehas@gamil.com
2      Mark     chem  74.00    Football     marks@gamil.com
3     Divas      Bio  88.50  Athelitics     divas@gmail.com
4    Jamaal      Geo  89.00      Tennis   jammaal@gamil.com

In [66]:
df1

   Students Subjects  Marks      Sports               email
0  Ruckhika    Maths  79.50     Cricket  ruchhika@gamil.com
1      Neha      Phy  83.75   Badminton     nehas@gamil.com
2      Mark     chem  74.00    Football     marks@gamil.com
3     Divas      Bio  88.50  Athelitics     divas@gmail.com
4    Jamaal      Geo  89.00      Tennis   jammaal@gamil.com

In [67]:
df1["Sports"]

0       Cricket
1     Badminton
2      Football
3    Athelitics
4        Tennis
Name: Sports, dtype: object

In [68]:
df1.set_index("Sports",inplace=True)

In [69]:
df1

            Students Subjects  Marks               email
Sports
Cricket     Ruckhika    Maths  79.50  ruchhika@gamil.com
Badminton       Neha      Phy  83.75     nehas@gamil.com
Football        Mark     chem  74.00     marks@gamil.com
Athelitics     Divas      Bio  88.50     divas@gmail.com
Tennis        Jamaal      Geo  89.00   jammaal@gamil.com

In [70]:
df1.index

Index(['Cricket', 'Badminton', 'Football', 'Athelitics', 'Tennis'], dtype='object', name='Sports')

In [71]:
df1.loc["Cricket"]

Students              Ruckhika
Subjects                 Maths
Marks                     79.5
email       ruchhika@gamil.com
Name: Cricket, dtype: object

In [72]:
df1.reset_index(inplace=True)

In [73]:
df1

       Sports  Students Subjects  Marks               email
0     Cricket  Ruckhika    Maths  79.50  ruchhika@gamil.com
1   Badminton      Neha      Phy  83.75     nehas@gamil.com
2    Football      Mark     chem  74.00     marks@gamil.com
3  Athelitics     Divas      Bio  88.50     divas@gmail.com
4      Tennis    Jamaal      Geo  89.00   jammaal@gamil.com

In [74]:
filt=((df1["Sports"]=="Cricket") & (df1['Subjects']=='Maths' ))

In [75]:
df1[~filt]

       Sports Students Subjects  Marks              email
1   Badminton     Neha      Phy  83.75    nehas@gamil.com
2    Football     Mark     chem  74.00    marks@gamil.com
3  Athelitics    Divas      Bio  88.50    divas@gmail.com
4      Tennis   Jamaal      Geo  89.00  jammaal@gamil.com

In [76]:
df1.columns

Index(['Sports', 'Students', 'Subjects', 'Marks', 'email'], dtype='object')

In [77]:
df1.columns=["Sports",'Name','Sub','Marks','gamil']
df1

       Sports      Name    Sub  Marks               gamil
0     Cricket  Ruckhika  Maths  79.50  ruchhika@gamil.com
1   Badminton      Neha    Phy  83.75     nehas@gamil.com
2    Football      Mark   chem  74.00     marks@gamil.com
3  Athelitics     Divas    Bio  88.50     divas@gmail.com
4      Tennis    Jamaal    Geo  89.00   jammaal@gamil.com

In [78]:
df1.columns=[x.upper() for x in df1.columns]
df1

       SPORTS      NAME    SUB  MARKS               GAMIL
0     Cricket  Ruckhika  Maths  79.50  ruchhika@gamil.com
1   Badminton      Neha    Phy  83.75     nehas@gamil.com
2    Football      Mark   chem  74.00     marks@gamil.com
3  Athelitics     Divas    Bio  88.50     divas@gmail.com
4      Tennis    Jamaal    Geo  89.00   jammaal@gamil.com

In [79]:
df1.columns=df1.columns.str.replace(' ',"_")

In [80]:
df1

       SPORTS      NAME    SUB  MARKS               GAMIL
0     Cricket  Ruckhika  Maths  79.50  ruchhika@gamil.com
1   Badminton      Neha    Phy  83.75     nehas@gamil.com
2    Football      Mark   chem  74.00     marks@gamil.com
3  Athelitics     Divas    Bio  88.50     divas@gmail.com
4      Tennis    Jamaal    Geo  89.00   jammaal@gamil.com

In [84]:
df1.loc[3]=["Hockey",'Raj','CS','90',"raj@gamil.com"]
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha    Phy  83.75     nehas@gamil.com
2   Football      Mark   chem   74.0     marks@gamil.com
3     Hockey       Raj     CS     90       raj@gamil.com
4     Tennis    Jamaal    Geo   89.0   jammaal@gamil.com

In [89]:
df1.loc[2,['NAME','GAMIL']]=['Doe','johdoe@email.com']
df1

,SPORTS,NAME,SUB,MARKS,GAMIL,name,email
0,Cricket,Ruckhika,Maths,79.5,ruchhika@gamil.com,NaN,NaN
1,Badminton,Neha,Phy,83.75,nehas@gamil.com,NaN,NaN
2,Football,Doe,chem,74.0,johdoe@email.com,Doe,johdoe@email.com
3,Hockey,Raj,CS,90,raj@gamil.com,NaN,NaN
4,Tennis,Smith,Geo,89.0,jammaal@gamil.com,NaN,NaN

In [90]:
df1 = df1.drop(columns=['name', 'email'])
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha    Phy  83.75     nehas@gamil.com
2   Football       Doe   chem   74.0    johdoe@email.com
3     Hockey       Raj     CS     90       raj@gamil.com
4     Tennis     Smith    Geo   89.0   jammaal@gamil.com

In [91]:
df1.loc[4,'NAME']='Smith'

In [92]:
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha    Phy  83.75     nehas@gamil.com
2   Football       Doe   chem   74.0    johdoe@email.com
3     Hockey       Raj     CS     90       raj@gamil.com
4     Tennis     Smith    Geo   89.0   jammaal@gamil.com

In [94]:
df1.at[4,'NAME']='Virat'
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha    Phy  83.75     nehas@gamil.com
2   Football       Doe   chem   74.0    johdoe@email.com
3     Hockey       Raj     CS     90       raj@gamil.com
4     Tennis     Virat    Geo   89.0   jammaal@gamil.com

In [101]:
filt=(df1['NAME']=='Raj')
df1[filt]['GAMIL']='raj@email.com'

/tmp/ipykernel_474/2587963784.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[filt]['GAMIL']='raj@email.com'

In [104]:
filt=(df1['NAME']=='Raj')
df1.loc[filt,'GAMIL']='raj@email.com'
df1

      SPORTS      NAME    SUB  MARKS               GAMIL
0    Cricket  Ruckhika  Maths   79.5  ruchhika@gamil.com
1  Badminton      Neha    Phy  83.75     nehas@gamil.com
2   Football       Doe   chem   74.0    johdoe@email.com
3     Hockey       Raj     CS     90       raj@email.com
4     Tennis     Virat    Geo   89.0   jammaal@gamil.com